# coding: utf-8

# flake8: noqa
"""
    Placement Controller

    Baseline Placement Controller for Decentralized Control Plance

    The version of the OpenAPI document: 0.1.0
    Contact: all-hiro@hiro-microdatacenters.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from placement_controller_client.models.application_model import ApplicationModel
    from placement_controller_client.models.http_validation_error import HTTPValidationError
    from placement_controller_client.models.validation_error import ValidationError
    from placement_controller_client.models.validation_error_loc_inner import ValidationErrorLocInner
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from placement_controller_client.models.application_model import ApplicationModel
from placement_controller_client.models.http_validation_error import HTTPValidationError
from placement_controller_client.models.validation_error import ValidationError
from placement_controller_client.models.validation_error_loc_inner import ValidationErrorLocInner

""",
            name=__name__,
            doc=__doc__,
        )
    )
